# No [build-system], no [project] -> uv won't try to build your code.
# It will only create a venv and install these dependencies.

[tool.uv]
managed = true
default-groups = ["deps"]

required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]

[dependency-groups]
deps = [
  # Core
  "numpy",
  "scipy",
  "dill",
  "pandas",
  "numba",
  "pyteomics",
  "pymzml",
  "psims",
  "brain-isotopic-distribution",
  "biosaur2",
  "lxml",
  "regex",
  "tqdm",
  "peppy_sage",

  # Visualization
  "matplotlib",
  "seaborn",
  "plotly",
  "matplotlib-venn",
  "upsetplot",
  "pillow",

  # Data engineering / IO
  "pyarrow",
  "polars",

  # Classical ML / stats
  "scikit-learn",
  "xgboost",
  "statsmodels",
  "joblib",

  # Optimization / math extras
  "cvxopt",
  "ptinnls",

  # Profiling & perf tools
  "line-profiler",
  "memory-profiler",
  "pyinstrument",

  # GUI (Qt + optional Tk themes)
  "PySide6",
  "shiboken6",
  "sv-ttk",
  "ttkthemes",

  # OS-specific helper
  "pywin32; platform_system == 'Windows'",
  "pythonnet",

  # TensorFlow per platform
  # Mac
  "tensorflow==2.15.1; platform_system == 'Darwin' and platform_machine == 'arm64'",
  "tensorflow-metal==1.2.*; platform_system == 'Darwin' and platform_machine == 'arm64'",

  # Windows
  "tensorflow-intel==2.15.1; sys_platform == 'win32' and platform_machine == 'AMD64'",

  # Linux
  "tensorflow==2.15.1; platform_system == 'Linux'",

  # Important: keep TF-Keras (2.15) and block standalone Keras 3
  "keras==2.15.*",

  # Shared TF tooling
  "tensorboard",
  "tensorboard-data-server",
  "tensorflow-io-gcs-filesystem",

  # Testing
  "pytest",
  "pytest-cov"
]
dev = [
    "pyside6<6.8",
]

[tool.coverage.run]
omit = [
    "src/run_jmod_from_GUI.py",
    "src/utils/gui_utils.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
