[loggers]
keys=root,appLogger

[handlers]
keys=consoleHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=WARNING
handlers=consoleHandler

[logger_appLogger]
level=DEBUG
handlers=consoleHandler
qualname=appLogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=simpleFormatter
args=(sys.stdout,)

# [handler_fileHandler]  #this is set in run_jmod main() now to point to a file in the output dir
# class=FileHandler
# level=INFO
# formatter=simpleFormatter
# args=('jmod.log', 'a')

[formatter_simpleFormatter]
format=%(asctime)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S




